# Makefile autogenerated by Dyi on November 19, 2019
#
# Main target: all
# Sources:  src/index.js  src/postJson.js  src/test.js 

.DEFAULT_GOAL := all


.PHONY: docs
docs: k-hjpuv9f3 k-erqf6mq9 k-h2r6ouof k-75vqay0m k-5k4o7aob k-qjos1srj


.PHONY: debug
debug: k-lk4bambl


.PHONY: c-wrya8kpp
c-wrya8kpp: lib/index.js lib/postJson.js lib/test.js


.PHONY: build
build: c-wrya8kpp


.PHONY: test
test: k-2ukm5j0s k-rsiv50v5


.PHONY: update
update: k-vtyjlds0


.PHONY: major
major: k-j62ljpwb k-6tdfy7h1 k-0jb7l92j


.PHONY: minor
minor: k-demrm77c k-i9d4k0rr k-seeomuhu


.PHONY: patch
patch: k-kpsa8a4q k-uvjhnbn1 k-3jvv25w8


.PHONY: prepare
prepare: lib




.PHONY: k-hjpuv9f3
k-hjpuv9f3:  
	./node_modules/.bin/git-hist history.md


.PHONY: k-erqf6mq9
k-erqf6mq9:  
	./node_modules/.bin/mustache package.json docs/readme.md | ./node_modules/.bin/stupid-replace '~USAGE~' -f docs/usage.md > readme.md


.PHONY: k-h2r6ouof
k-h2r6ouof:  
	cat history.md >> readme.md


.PHONY: k-75vqay0m
k-75vqay0m:  
	mkdir -p ./man/man1


.PHONY: k-5k4o7aob
k-5k4o7aob:  
	pandoc -s -f markdown -t man readme.md > ./man/man1/vz-biblio2json.1


.PHONY: k-qjos1srj
k-qjos1srj:  
	hub cm 'update docs and history.md'


.PHONY: k-lk4bambl
k-lk4bambl:  
	make && node ./index.js convert ./test/biblio.bib


.PHONY: k-mbl224xb
k-mbl224xb:  
	((echo '#!/usr/bin/env node') && cat ./lib/index.js) > index.js


.PHONY: k-irhjy29o
k-irhjy29o:  
	chmod +x ./index.js


.PHONY: all
all: 
	make build 
	make k-mbl224xb 
	make k-irhjy29o  


.PHONY: k-2ukm5j0s
k-2ukm5j0s:  
	make all


.PHONY: k-rsiv50v5
k-rsiv50v5:  
	./node_modules/.bin/mocha ./lib/test.js


.PHONY: k-vtyjlds0
k-vtyjlds0:  
	make clean && ./node_modules/.bin/babel configure.js | node


.PHONY: k-j62ljpwb
k-j62ljpwb:  
	make all


.PHONY: k-6tdfy7h1
k-6tdfy7h1:  
	make docs


.PHONY: k-0jb7l92j
k-0jb7l92j:  
	./node_modules/.bin/xyz -i major


.PHONY: k-demrm77c
k-demrm77c:  
	make all


.PHONY: k-i9d4k0rr
k-i9d4k0rr:  
	make docs


.PHONY: k-seeomuhu
k-seeomuhu:  
	./node_modules/.bin/xyz -i minor


.PHONY: k-kpsa8a4q
k-kpsa8a4q:  
	make all


.PHONY: k-uvjhnbn1
k-uvjhnbn1:  
	make docs


.PHONY: k-3jvv25w8
k-3jvv25w8:  
	./node_modules/.bin/xyz -i patch


.PHONY: clean
clean:  
	rm -f lib/index.js
	rm -f lib/postJson.js
	rm -f lib/test.js




lib/index.js: src/index.js 
	./node_modules/.bin/babel src/index.js -o ./lib/index.js

lib/postJson.js: src/postJson.js 
	./node_modules/.bin/babel src/postJson.js -o ./lib/postJson.js

lib/test.js: src/test.js 
	./node_modules/.bin/babel src/test.js -o ./lib/test.js

lib: 
	mkdir -p lib

