# Makefile autogenerated by Dyi on November 19, 2019
#
# Main target: all
# Sources:  src/index.js  src/postJson.js  src/test.js 

.DEFAULT_GOAL := all


.PHONY: docs
docs: k-auv1wypj k-cd84bji8 k-ujy4hgb7 k-k1elrqna k-k5mwdauk k-xsj0in2r


.PHONY: debug
debug: k-2hhju01m


.PHONY: c-hxn0bdhf
c-hxn0bdhf: lib/index.js lib/postJson.js lib/test.js


.PHONY: build
build: c-hxn0bdhf


.PHONY: test
test: k-5caq61ii k-ep7ffwg7


.PHONY: update
update: k-sb5ylypm


.PHONY: major
major: k-b0isvgfm k-uv9p84c2 k-ljx9lwrq


.PHONY: minor
minor: k-bf2j8iq2 k-xlbh24x2 k-aa5rdh8y


.PHONY: patch
patch: k-oal3bb87 k-kcenr134 k-jchcmh6n


.PHONY: prepare
prepare: lib




.PHONY: k-auv1wypj
k-auv1wypj:  
	./node_modules/.bin/git-hist history.md


.PHONY: k-cd84bji8
k-cd84bji8:  
	./node_modules/.bin/mustache package.json docs/readme.md | ./node_modules/.bin/stupid-replace '~USAGE~' -f docs/usage.md > readme.md


.PHONY: k-ujy4hgb7
k-ujy4hgb7:  
	cat history.md >> readme.md


.PHONY: k-k1elrqna
k-k1elrqna:  
	mkdir -p ./man/man1


.PHONY: k-k5mwdauk
k-k5mwdauk:  
	pandoc -s -f markdown -t man readme.md > ./man/man1/vz-biblio2json.1


.PHONY: k-xsj0in2r
k-xsj0in2r:  
	hub cm 'update docs and history.md'


.PHONY: k-2hhju01m
k-2hhju01m:  
	make && node ./index.js convert ./test/biblio.bib


.PHONY: k-su9wnshv
k-su9wnshv:  
	((echo '#!/usr/bin/env node') && cat ./lib/index.js) > index.js


.PHONY: k-flqcmw00
k-flqcmw00:  
	chmod +x ./index.js


.PHONY: all
all: 
	make build 
	make k-su9wnshv 
	make k-flqcmw00  


.PHONY: k-5caq61ii
k-5caq61ii:  
	make all


.PHONY: k-ep7ffwg7
k-ep7ffwg7:  
	./node_modules/.bin/mocha ./lib/test.js


.PHONY: k-sb5ylypm
k-sb5ylypm:  
	make clean && ./node_modules/.bin/babel configure.js | node


.PHONY: k-b0isvgfm
k-b0isvgfm:  
	make all


.PHONY: k-uv9p84c2
k-uv9p84c2:  
	make docs


.PHONY: k-ljx9lwrq
k-ljx9lwrq:  
	./node_modules/.bin/xyz -i major


.PHONY: k-bf2j8iq2
k-bf2j8iq2:  
	make all


.PHONY: k-xlbh24x2
k-xlbh24x2:  
	make docs


.PHONY: k-aa5rdh8y
k-aa5rdh8y:  
	./node_modules/.bin/xyz -i minor


.PHONY: k-oal3bb87
k-oal3bb87:  
	make all


.PHONY: k-kcenr134
k-kcenr134:  
	make docs


.PHONY: k-jchcmh6n
k-jchcmh6n:  
	./node_modules/.bin/xyz -i patch


.PHONY: clean
clean:  
	rm -f lib/index.js
	rm -f lib/postJson.js
	rm -f lib/test.js




lib/index.js: src/index.js 
	./node_modules/.bin/babel src/index.js -o ./lib/index.js

lib/postJson.js: src/postJson.js 
	./node_modules/.bin/babel src/postJson.js -o ./lib/postJson.js

lib/test.js: src/test.js 
	./node_modules/.bin/babel src/test.js -o ./lib/test.js

lib: 
	mkdir -p lib

